### ISSUE TITLE
orc cave fel

### ISSUE THREAD

**Issue by Kylezzz101** [ageofbritannia/AOBShardIssueReport#4]
there is no way to return to level 1 teleporters not there?

**Comment by Kylezzz101** [comment]
![image](https://user-images.githubusercontent.com/41597369/218639579-031006aa-5ded-4937-8274-b6b0bd3b5b27.png)

**Comment by ageofbritannia** [comment]
Teleporters have now been added to this area to fix the issue! Thanks
