### ISSUE TITLE
update quest text for unholy souls and rebalance soul drops

### ISSUE THREAD

**Issue by Kylezzz101** [ageofbritannia/AOBShardIssueReport#7]
the soul drops are abysmal the quest turn in is 20 atm quest says 300
![image](https://user-images.githubusercontent.com/41597369/221462722-c6eabd0c-fe9e-4f06-a553-1fbc3aa15a09.png)

**Comment by Kylezzz101** [comment]
as we;; ive only seen them drop of the mages

**Comment by ageofbritannia** [comment]
Well spotted! Fixed and will be pushed over in next update thanks!
